-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'a0c6379d1da6e019' HASH '9ecfdd565b6997a2eb6ee4d597611ccdd90aabcd48ba14f2c5aad63f9f775431' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 8) NOT NULL,
    "QUANTITY" INTEGER,
    "TOTAL_PRICE" FLOAT(53),
    "PRODUCT_ID" BIGINT,
    "USER_ID" BIGINT
);    
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;  
INSERT INTO "PUBLIC"."ORDERS" VALUES
(8, 2, 300.0, NULL, 11),
(9, 2, 300.0, NULL, 11);      
CREATE CACHED TABLE "PUBLIC"."ORDERS_TO"(
    "ORDER_ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL
);              
ALTER TABLE "PUBLIC"."ORDERS_TO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8E" PRIMARY KEY("ORDER_ID", "PRODUCT_ID");               
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS_TO;               
INSERT INTO "PUBLIC"."ORDERS_TO" VALUES
(8, 315),
(8, 316),
(8, 313),
(8, 312);           
CREATE CACHED TABLE "PUBLIC"."PRODUCTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 349) NOT NULL,
    "CATEGORY" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PRICE" FLOAT(53),
    "SALE_PRICE" FLOAT(53),
    "STOCK" INTEGER,
    "IMAGE_PATH" CHARACTER VARYING(255),
    "IMAGE" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."PRODUCTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");     
-- 46 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCTS;               
INSERT INTO "PUBLIC"."PRODUCTS" VALUES
(303, 'mens', 'acg-lowcate-mens-shoes-7Px0Lq', 'acglowcate', 75.0, NULL, 4, NULL, '/images/acg-lowcate-mens-shoes-7Px0Lq.png'),
(304, 'mens', 'acg-lowcate-x-future-movement-mens-shoes-sKqFzL', 'acglowcate-x-future-movement', 181.0, NULL, 15, NULL, '/images/acg-lowcate-x-future-movement-mens-shoes-sKqFzL.png'),
(305, 'mens', 'acg-mountain-fly-low-gore-tex-se-mens-shoes-Xc5LHq', 'acgmountain-fly-low-gore-tex-se', 112.0, NULL, 14, NULL, '/images/acg-mountain-fly-low-gore-tex-se-mens-shoes-Xc5LHq.png'),
(306, 'mens', 'air-force-1-07-lx-mens-shoes-D2ZCMj', 'airforce-1-07-lx', 139.0, NULL, 15, NULL, '/images/air-force-1-07-lx-mens-shoes-D2ZCMj.png'),
(307, 'mens', 'air-force-1-07-lx-nbhd-mens-shoes-qnMX3r', 'airforce-1-07-lx-nbhd', 105.0, NULL, 16, NULL, '/images/air-force-1-07-lx-nbhd-mens-shoes-qnMX3r.png'),
(308, 'mens', 'air-force-1-low-retro-mens-shoes-1VHstQ', 'airforce-1-low-retro', 167.0, NULL, 0, NULL, '/images/air-force-1-low-retro-mens-shoes-1VHstQ.png'),
(309, 'mens', 'air-force-1-low-retro-mens-shoes-53gMmt', 'airforce-1-low-retro', 77.0, NULL, 18, NULL, '/images/air-force-1-low-retro-mens-shoes-53gMmt.png'),
(310, 'big-kids', 'air-force-1-lv8-2-big-kids-shoes-1JQL4Z', 'airforce-1-lv8-2', 142.0, NULL, 10, NULL, '/images/air-force-1-lv8-2-big-kids-shoes-1JQL4Z.png'),
(311, 'big-kids', 'air-force-1-lv8-big-kids-shoes-1lGPrs', 'airforce-1-lv8', 124.0, NULL, 9, NULL, '/images/air-force-1-lv8-big-kids-shoes-1lGPrs.png'),
(312, 'big-kids', 'air-force-1-lv8-big-kids-shoes-3f2DJj', 'airforce-1-lv8', 149.0, NULL, 6, NULL, '/images/air-force-1-lv8-big-kids-shoes-3f2DJj.png'),
(313, 'big-kids', 'air-force-1-lv8-big-kids-shoes-5D3Vm7', 'airforce-1-lv8', 95.0, NULL, 18, NULL, '/images/air-force-1-lv8-big-kids-shoes-5D3Vm7.png'),
(314, 'big-kids', 'air-force-1-lv8-big-kids-shoes-bGNdjh', 'airforce-1-lv8', 158.0, NULL, 6, NULL, '/images/air-force-1-lv8-big-kids-shoes-bGNdjh.png'),
(315, 'big-kids', 'air-force-1-lv8-big-kids-shoes-BktXWT', 'airforce-1-lv8', 180.0, NULL, 8, NULL, '/images/air-force-1-lv8-big-kids-shoes-BktXWT.png'),
(316, 'big-kids', 'air-force-1-lv8-big-kids-shoes-HPbjCf', 'airforce-1-lv8', 99.0, NULL, 19, NULL, '/images/air-force-1-lv8-big-kids-shoes-HPbjCf.png'),
(317, 'little-kids', 'air-max-270-little-kids-shoes-RStNgd', 'airmax-270', 140.0, NULL, 14, NULL, '/images/air-max-270-little-kids-shoes-RStNgd.png'),
(318, 'big-kids', 'air-max-90-ltr-se-big-kids-shoes-rzfNXZ', 'airmax-90-ltr-se', 134.0, NULL, 7, NULL, '/images/air-max-90-ltr-se-big-kids-shoes-rzfNXZ.png'),
(319, 'little-kids', 'air-max-90-ltr-se-little-kids-shoes-rvC8r8', 'airmax-90-ltr-se', 133.0, NULL, 18, NULL, '/images/air-max-90-ltr-se-little-kids-shoes-rvC8r8.png'),
(320, 'mens', 'air-max-90-mens-shoes-6mml4F', 'airmax-90', 129.0, NULL, 9, NULL, '/images/air-max-90-mens-shoes-6mml4F.png'),
(321, 'mens', 'air-max-90-mens-shoes-JdKKmQ', 'airmax-90', 150.0, NULL, 2, NULL, '/images/air-max-90-mens-shoes-JdKKmQ.png'),
(322, 'mens', 'air-max-90-mens-shoes-v7mbfF', 'airmax-90', 144.0, NULL, 7, NULL, '/images/air-max-90-mens-shoes-v7mbfF.png'),
(323, 'mens', 'air-max-90-mens-shoes-vJVvD1', 'airmax-90', 165.0, NULL, 8, NULL, '/images/air-max-90-mens-shoes-vJVvD1.png'),
(324, 'mens', 'air-max-90-premium-mens-shoes-9sg476', 'airmax-90-premium', 85.0, NULL, 19, NULL, '/images/air-max-90-premium-mens-shoes-9sg476.png'),
(325, 'mens', 'air-max-90-se-mens-shoes-2VX0QQ', 'airmax-90-se', 168.0, NULL, 20, NULL, '/images/air-max-90-se-mens-shoes-2VX0QQ.png'),
(326, 'womens', 'air-max-95-lx-womens-shoes-5PsPNn', 'airmax-95-lx', 147.0, NULL, 0, NULL, '/images/air-max-95-lx-womens-shoes-5PsPNn.png'),
(327, 'big-kids', 'air-max-97-big-kids-shoes-tLQrln', 'airmax-97', 99.0, NULL, 6, NULL, '/images/air-max-97-big-kids-shoes-tLQrln.png'),
(328, 'mens', 'air-max-97-mens-shoes-6mZC1L', 'airmax-97', 71.0, NULL, 5, NULL, '/images/air-max-97-mens-shoes-6mZC1L.png'),
(329, 'mens', 'air-max-97-premium-mens-shoes-vf75n4', 'airmax-97-premium', 62.0, NULL, 3, NULL, '/images/air-max-97-premium-mens-shoes-vf75n4.png'),
(330, 'big-kids', 'air-max-97-se-big-kids-shoes-Clc2gq', 'airmax-97-se', 142.0, NULL, 5, NULL, '/images/air-max-97-se-big-kids-shoes-Clc2gq.png');        
INSERT INTO "PUBLIC"."PRODUCTS" VALUES
(331, 'big-kids', 'air-max-97-se-big-kids-shoes-pn6x2N', 'airmax-97-se', 74.0, NULL, 15, NULL, '/images/air-max-97-se-big-kids-shoes-pn6x2N.png'),
(332, 'womens', 'air-max-97-womens-shoes-Fr6rM4', 'airmax-97', 136.0, NULL, 14, NULL, '/images/air-max-97-womens-shoes-Fr6rM4.png'),
(333, 'little-kids', 'air-max-axis-little-kids-shoes-tCLNp0', 'airmax-axis', 180.0, NULL, 20, NULL, '/images/air-max-axis-little-kids-shoes-tCLNp0.png'),
(334, 'womens', 'air-max-bliss-lx-womens-shoes-rJ0q5H', 'airmax-bliss-lx', 122.0, NULL, 10, NULL, '/images/air-max-bliss-lx-womens-shoes-rJ0q5H.png'),
(335, 'big-kids', 'air-max-bolt-big-kids-shoes-W87KDt', 'airmax-bolt', 68.0, NULL, 1, NULL, '/images/air-max-bolt-big-kids-shoes-W87KDt.png'),
(336, 'big-kids', 'air-max-motif-next-nature-big-kids-shoes-2TxsK7', 'airmax-motif-next-nature', 187.0, NULL, 12, NULL, '/images/air-max-motif-next-nature-big-kids-shoes-2TxsK7.png'),
(337, 'mens', 'air-max-penny-mens-shoes-p3DjvD', 'airmax-penny', 184.0, NULL, 15, NULL, '/images/air-max-penny-mens-shoes-p3DjvD.png'),
(338, 'big-kids', 'air-max-plus-big-kids-shoe-xcLrlD', 'airmax-plus', 122.0, NULL, 1, NULL, '/images/air-max-plus-big-kids-shoe-xcLrlD.png'),
(339, 'big-kids', 'air-max-plus-big-kids-shoes-CzQBp3', 'airmax-plus', 122.0, NULL, 11, NULL, '/images/air-max-plus-big-kids-shoes-CzQBp3.png'),
(340, 'little-kids', 'air-max-plus-little-kids-shoes-fkZwCW', 'airmax-plus', 191.0, NULL, 10, NULL, '/images/air-max-plus-little-kids-shoes-fkZwCW.png'),
(341, 'little-kids', 'air-max-plus-little-kids-shoes-kX4fG4', 'airmax-plus', 129.0, NULL, 0, NULL, '/images/air-max-plus-little-kids-shoes-kX4fG4.png'),
(342, 'mens', 'air-max-pulse-mens-shoes-ShS3tL', 'airmax-pulse', 81.0, NULL, 10, NULL, '/images/air-max-pulse-mens-shoes-ShS3tL.png'),
(343, 'womens', 'air-max-pulse-womens-shoes-TLnkLm', 'airmax-pulse', 79.0, NULL, 2, NULL, '/images/air-max-pulse-womens-shoes-TLnkLm.png'),
(344, 'womens', 'air-max-scorpion-flyknit-womens-shoes-370PFr', 'airmax-scorpion-flyknit', 83.0, NULL, 16, NULL, '/images/air-max-scorpion-flyknit-womens-shoes-370PFr.png'),
(345, 'big-kids', 'air-max-systm-big-kids-shoes-jh1PDw', 'airmax-systm', 94.0, NULL, 12, NULL, '/images/air-max-systm-big-kids-shoes-jh1PDw.png'),
(346, 'little-kids', 'air-max-systm-little-kids-shoes-bpKSzc', 'airmax-systm', 197.0, NULL, 15, NULL, '/images/air-max-systm-little-kids-shoes-bpKSzc.png'),
(347, 'womens', 'air-max-systm-womens-shoes-Cz5zxV', 'airmax-systm', 177.0, NULL, 4, NULL, '/images/air-max-systm-womens-shoes-Cz5zxV.png'),
(348, 'mens', 'air-max-terrascape-90-mens-shoes-61rLc8', 'airmax-terrascape-90', 160.0, NULL, 5, NULL, '/images/air-max-terrascape-90-mens-shoes-61rLc8.png');               
CREATE CACHED TABLE "PUBLIC"."REVIEWS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "CONTENT" CHARACTER VARYING(255),
    "RATING" INTEGER,
    "PRODUCT_ID" BIGINT,
    "USER_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."REVIEWS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REVIEWS; 
CREATE CACHED TABLE "PUBLIC"."USER_FAVORITES"(
    "USER_ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."USER_FAVORITES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FA" PRIMARY KEY("USER_ID", "PRODUCT_ID");           
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USER_FAVORITES;          
INSERT INTO "PUBLIC"."USER_FAVORITES" VALUES
(11, 311),
(11, 310);          
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 12) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "ROLE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);     
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'new@example.com', 'New', 'User', 'new_password', 'ROLE_USER', 'new_user'),
(9, 'testmail@gmail.com', NULL, NULL, '$2a$10$1zRTB.3pjCuI3WlYHiKddexpAsgl3P6Tc3pCA7JT5ur5W3UXSLfY.', 'ROLE_USER', 'othanos'),
(10, 'example21@gmail.com', NULL, NULL, '$2a$10$O4PuJBnfRMgEvqs4Yc0c..pRFwVekhuTNR6YqyWK0oTl7m4UA2wwi', 'ROLE_USER', 'odion'),
(11, 'okurios@example.com', NULL, NULL, '$2a$10$Pgv6zxGKgPuMr/IL2WNbT.ezsCDznlTze8Apix7yQjksMrFd58gHy', 'ROLE_USER', 'okurios');        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UKR43AF9AP4EDM43MMTQ01ODDJ6" UNIQUE("USERNAME");        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE("EMAIL");           
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK32QL8UBNTJ5UH44PH9659TIIH" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."ORDERS_TO" ADD CONSTRAINT "PUBLIC"."FKHCMOTI1J50US0I8U8PYDIIB62" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."ORDERS"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."USER_FAVORITES" ADD CONSTRAINT "PUBLIC"."FK4SV7B9W9ADR0FJNC4U10EXLWM" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."REVIEWS" ADD CONSTRAINT "PUBLIC"."FKCGY7QJC1R99DP117Y9EN6LXYE" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKKP5K52QTIYGD8JKAG4HAYD0QG" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCTS"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."USER_FAVORITES" ADD CONSTRAINT "PUBLIC"."FKLEU0DBK5W8Y4VPN5TB7FNHRGV" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCTS"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."ORDERS_TO" ADD CONSTRAINT "PUBLIC"."FKML3IFMTXV7MJ6LEP3UDHMYO3I" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REVIEWS" ADD CONSTRAINT "PUBLIC"."FKPL51CEJPW4GY5SWFAR8BR9NGI" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCTS"("ID") NOCHECK;  
